# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["tables"]

highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            Renevant Cheetah
tagline:          'The periphery of ideas'
url:              https://renevantcheetah.github.io/
shorturl:         renevantcheetah.github.io

author:
  name:           'Vipul Maheshwari'
  url:            https://www.instagram.com/maheshwarivipul16/

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/renevantcheetah/renevantcheetah.github.io

# This is the list of pages to include in the header of the website.
pages_list:  

  Feed: '/feed/'
  Dump: '/categories/'
  Me: '/me/'
  

  # Feed: '/atom.xml'


# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
